// app/layout.tsx (or your RootLayout file)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/Footer";
import { CartProvider } from "./Context/CartContext";
import CartIcon from "./components/CartIcon";
import { LoginProvider } from "./Context/LoginContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
      <LoginProvider>
        <Navbar /> {/* Navbar is included within the body */}
        <CartProvider>
         

          <CartIcon />
          <main className="flex-grow">
            {children}
       
          </main>
          </CartProvider>
          </LoginProvider>

        
        <Footer />
      </body>
    </html>
  );
}
